/* CAPRICHOS-CONTABLE: módulo local de cierre diario NRUS. No emite comprobantes. */
(()=>{'use strict';
const UNDO_KEY='caprichos-nrus-ultimo-eliminado-v2';
 const KEY='caprichos-nrus-ventas-v1', BUY='compras-al-dia-v1';
const el=(id)=>document.getElementById(id), fmt=n=>'S/ '+Number(n||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2});
const iso=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const read=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}};
const amount=x=>{const n=Number(x);return Number.isFinite(n)&&n>=0?Math.round(n*100)/100:NaN};
const safe=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=document.createElement('style');css.textContent=`#nr-panel{max-width:1100px;margin:24px auto;padding:20px;border:2px solid #166534;border-radius:16px;background:#f8fffa;color:#163026;font-family:system-ui,sans-serif}#nr-panel h2{font-size:1.45rem;margin:0 0 8px}#nr-panel .nr-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(165px,1fr));gap:12px;margin:14px 0}#nr-panel label{display:block;font-weight:650;font-size:13px;margin-bottom:5px}#nr-panel input,#nr-panel select{width:100%;box-sizing:border-box;padding:11px;border:1px solid #9ab7a4;border-radius:8px;background:white;color:#111}#nr-panel button{padding:10px 14px;border:0;border-radius:8px;background:#166534;color:white;cursor:pointer;margin:3px}#nr-panel button.nr-secondary{background:#425e50}#nr-panel button.nr-delete{background:#a12c2c}#nr-panel button.nr-undo{background:#82561c}#nr-panel button:focus-visible{outline:3px solid #e8a849;outline-offset:2px}#nr-panel .nr-card{background:white;border:1px solid #c9dfcf;border-radius:9px;padding:12px}#nr-panel .nr-warning{background:#fff3d1;padding:12px;border-radius:8px}#nr-panel .nr-danger{background:#ffe1e1;padding:12px;border-radius:8px}#nr-panel table{width:100%;border-collapse:collapse}#nr-panel th,#nr-panel td{padding:7px;text-align:left;border-bottom:1px solid #d6e5db;font-size:13px}#nr-panel .nr-scroll{overflow:auto}#nr-panel .nr-muted{font-size:13px;color:#52675a}`;document.head.append(css);
const box=document.createElement('section');box.id='nr-panel';box.innerHTML=`<h2>📒 Control Nuevo RUS — cierre diario</h2><p class="nr-muted">Registro interno sin internet. No reemplaza la emisión de boletas físicas/electrónicas ni la declaración ante SUNAT. Las cifras tributarias deben confirmarse si cambia la normativa.</p><div class="nr-grid"><div><label for="nr-date">Fecha de venta</label><input id="nr-date" type="date"></div><div><label for="nr-physical">Boletas físicas (S/)</label><input id="nr-physical" type="number" min="0" step="0.01" value="0"></div><div><label for="nr-electronic">Boletas electrónicas (S/)</label><input id="nr-electronic" type="number" min="0" step="0.01" value="0"></div><div><label for="nr-global">Ventas sustentadas en boleta global (S/)</label><input id="nr-global" type="number" min="0" step="0.01" value="0"></div></div><p class="nr-muted">No dupliques operaciones: cada venta debe figurar en una sola casilla. La boleta global solo corresponde cuando la normativa lo permita y se haya emitido el comprobante exigible.</p><button id="nr-save">Guardar cierre diario</button><button class="nr-secondary" id="nr-export">Descargar respaldo de ventas</button><label style="display:inline-block;margin:8px">Restaurar ventas <input id="nr-import" type="file" accept="application/json,.json"></label><div class="nr-grid" id="nr-stats"></div><div id="nr-alert"></div><h3>Últimos cierres registrados</h3><div id="nr-undo-box" role="status" aria-live="polite"></div><div class="nr-scroll"><table><thead><tr><th>Fecha</th><th>Físicas</th><th>Electrónicas</th><th>Global</th><th>Total</th><th>Acción</th></tr></thead><tbody id="nr-history"></tbody></table></div><p class="nr-muted">Los respaldos de compras/fotos de la aplicación original son independientes del respaldo de ventas de este módulo. Guarda ambos archivos en un USB.</p>`;
(document.querySelector('main')||document.body).append(box);el('nr-date').value=iso();
function purchases(){try{const d=JSON.parse(localStorage.getItem(BUY)||'{}');return Array.isArray(d.rows)?d.rows:[]}catch{return []}}
function rowTotal(r){for(const k of ['total','importeTotal','importe_total','montoTotal','monto','importe']){const n=Number(r[k]);if(Number.isFinite(n)&&n>=0)return n}return 0}
function refresh(){const rows=read(),month=el('nr-date').value.slice(0,7),year=month.slice(0,4);const v=rows.filter(r=>r.fecha.startsWith(month)).reduce((a,r)=>a+r.fisicas+r.electronicas+r.global,0);const va=rows.filter(r=>r.fecha.startsWith(year)).reduce((a,r)=>a+r.fisicas+r.electronicas+r.global,0);const ps=purchases();const pm=ps.filter(r=>String(r.periodo||r.fecha||'').startsWith(month)).reduce((a,r)=>a+rowTotal(r),0);const pa=ps.filter(r=>String(r.periodo||r.fecha||'').startsWith(year)).reduce((a,r)=>a+rowTotal(r),0);const top=Math.max(v,pm),annual=Math.max(va,pa),cat=top<=5000?1:top<=8000?2:0;el('nr-stats').innerHTML=`<div class="nr-card"><b>Ventas del mes</b><p>${fmt(v)}</p></div><div class="nr-card"><b>Compras del mes*</b><p>${fmt(pm)}</p></div><div class="nr-card"><b>Categoría estimada</b><p>${cat?'Categoría '+cat:'Fuera del límite mensual'}</p></div><div class="nr-card"><b>Cuota estimada</b><p>${cat?fmt(cat===1?20:50):'Revisar con SUNAT'}</p></div><div class="nr-card"><b>Ventas del año</b><p>${fmt(va)}</p></div><div class="nr-card"><b>Compras del año*</b><p>${fmt(pa)}</p></div>`;el('nr-alert').className=top>8000||annual>96000?'nr-danger':top>=4500||annual>=84000?'nr-warning':'';el('nr-alert').textContent=top>8000||annual>96000?'ALERTA: compras o ventas exceden el límite mensual de S/ 8,000 o anual de S/ 96,000. Verifica tu régimen con SUNAT.':top>=4500||annual>=84000?'PRECAUCIÓN: revisa tus compras y ventas. Desde S/ 5,000 se supera el tramo de categoría 1 y desde S/ 8,000 se supera el límite mensual del Nuevo RUS.':'Control preventivo: compara compras y ventas por separado. *Compras calculadas a partir de registros locales; verifica que estén completas y que los importes correspondan a adquisiciones computables.';
el('nr-history').innerHTML=rows.slice().sort((a,b)=>b.fecha.localeCompare(a.fecha)).slice(0,35).map(r=>`<tr><td>${safe(r.fecha)}</td><td>${fmt(r.fisicas)}</td><td>${fmt(r.electronicas)}</td><td>${fmt(r.global)}</td><td>${fmt(r.fisicas+r.electronicas+r.global)}</td><td><button data-date="${safe(r.fecha)}" class="nr-edit">Editar</button><button data-date="${safe(r.fecha)}" class="nr-delete">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="6">Todavía no hay cierres</td></tr>';
box.querySelectorAll('.nr-edit').forEach(b=>b.onclick=()=>{const r=read().find(x=>x.fecha===b.dataset.date);if(!r)return;el('nr-date').value=r.fecha;el('nr-physical').value=r.fisicas;el('nr-electronic').value=r.electronicas;el('nr-global').value=r.global;refresh();box.scrollIntoView({behavior:'smooth'})});
 box.querySelectorAll('.nr-delete').forEach(b=>b.onclick=()=>{const fecha=b.dataset.date,rows=read(),idx=rows.findIndex(r=>r.fecha===fecha);if(idx<0)return;const item=rows[idx];const total=item.fisicas+item.electronicas+item.global;if(!confirm(`¿Eliminar el cierre del ${fecha} por ${fmt(total)}?\n\nEsta acción modifica los totales del mes y del año. Podrás deshacerla mientras no borres el historial de recuperación.`))return;try{localStorage.setItem(UNDO_KEY,JSON.stringify(item));localStorage.setItem(KEY,JSON.stringify(rows.filter(r=>r.fecha!==fecha)));refresh();alert('Cierre eliminado. Puedes recuperarlo con el botón Deshacer eliminación.')}catch(e){alert('No se pudo eliminar el cierre. Conserva tu respaldo.')}});
 const undo=el('nr-undo-box');let deleted=null;try{deleted=JSON.parse(localStorage.getItem(UNDO_KEY)||'null')}catch{};
 undo.innerHTML=deleted&&/^\d{4}-\d{2}-\d{2}$/.test(deleted.fecha)?'<button class="nr-undo" id="nr-undo">Deshacer última eliminación</button>':'';
 if(deleted&&el('nr-undo'))el('nr-undo').onclick=()=>{const rows=read();if(rows.some(r=>r.fecha===deleted.fecha)){alert('Ya existe un cierre para esa fecha. No se sobrescribirá.');return;}try{localStorage.setItem(KEY,JSON.stringify([...rows,deleted]));localStorage.removeItem(UNDO_KEY);refresh();alert('Cierre recuperado correctamente.')}catch(e){alert('No se pudo recuperar el cierre.')}};
 }
el('nr-save').onclick=()=>{const fecha=el('nr-date').value,nums=['nr-physical','nr-electronic','nr-global'].map(id=>amount(el(id).value));if(!/^\d{4}-\d{2}-\d{2}$/.test(fecha)||new Date(fecha+'T12:00:00').toISOString().slice(0,10)!==fecha||nums.some(n=>!Number.isFinite(n))||nums.every(n=>n===0)){alert('Revisa la fecha y los importes. Debe existir una venta mayor a cero.');return}const rows=read(),existing=rows.findIndex(r=>r.fecha===fecha);if(existing>=0&&!confirm('Ya existe un cierre para esta fecha. ¿Deseas reemplazarlo?'))return;const row={fecha,fisicas:nums[0],electronicas:nums[1],global:nums[2],actualizado:new Date().toISOString()};if(existing>=0)rows[existing]=row;else rows.push(row);try{localStorage.setItem(KEY,JSON.stringify(rows));refresh();alert('Cierre guardado en este dispositivo. Recuerda realizar respaldos.')}catch(e){alert('No se pudo guardar. Libera espacio y descarga respaldos; no cierres la aplicación.') }};
el('nr-date').onchange=refresh;
el('nr-export').onclick=()=>{const data=JSON.stringify({app:'CAPRICHOS-NRUS-VENTAS',version:1,exportado:new Date().toISOString(),ventas:read()},null,2),blob=new Blob([data],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Respaldo_Ventas_NRUS_'+iso()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),15000)};
el('nr-import').onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const d=JSON.parse(await f.text());if(d.app!=='CAPRICHOS-NRUS-VENTAS'||!Array.isArray(d.ventas)||!d.ventas.every(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.fecha)&&['fisicas','electronicas','global'].every(k=>Number.isFinite(r[k])&&r[k]>=0)))throw Error('Formato inválido');if(!confirm('La restauración reemplazará todos los cierres de ventas de este dispositivo. ¿Continuar?'))return;localStorage.setItem(KEY,JSON.stringify(d.ventas));refresh();alert('Ventas restauradas correctamente.')}catch(err){alert('No se pudo restaurar: archivo inválido o almacenamiento insuficiente.')}};
refresh();})();
